In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import yt

In [ ]:
dir_main = "/mnt/sdceph/users/smenon/RHDSphereKrome/" 

fold_prfx = "GalaxyICsHydroDef"
dir_control = dir_main+fold_prfx
dir_allr = dir_main+fold_prfx+"AllBands"
dir_sne = dir_main+fold_prfx+"SNeOnly"
dir_both = dir_main+fold_prfx+"SNeRHD"

In [ ]:
file_prfx = "/RHDTurb_hdf5_"
fname_plot = "plt_cnt_"
fname_part = "part_"


frmt_num = "{:04d}"

In [ ]:
Ns_done = [201,381,130,63]

In [ ]:
dirss = [dir_control,
         dir_allr,
         dir_sne,
         dir_both]

In [ ]:
#read all the gas / sink particle masses that i need, then close all the files #look into how to explicitly cloe files / free up variables in yt

In [ ]:
%%time
part_files = [yt.load((dir+file_prfx+fname_part+frmt_num).format(n)) for dir,N in zip(dirss,Ns_done) for n in range(N)]

In [22]:
%%time
plot_files = [yt.load((dir+file_prfx+fname_plot+frmt_num).format(n)) for dir,N in zip(dirss,Ns_done) for n in range(N)]

yt : [INFO     ] 2025-02-05 07:53:55,089 Particle file found: RHDTurb_hdf5_part_0000
yt : [INFO     ] 2025-02-05 07:53:55,143 Parameters: current_time              = 0.0
yt : [INFO     ] 2025-02-05 07:53:55,144 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2025-02-05 07:53:55,146 Parameters: domain_left_edge          = [-4.31995267e+21 -4.31995267e+21 -4.31995267e+21]
yt : [INFO     ] 2025-02-05 07:53:55,148 Parameters: domain_right_edge         = [4.31995267e+21 4.31995267e+21 4.31995267e+21]
yt : [INFO     ] 2025-02-05 07:53:55,149 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-02-05 07:53:55,361 Particle file found: RHDTurb_hdf5_part_0001
yt : [INFO     ] 2025-02-05 07:53:55,411 Parameters: current_time              = 3902250095523.4453
yt : [INFO     ] 2025-02-05 07:53:55,413 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2025-02-05 07:53:55,414 Parameters: domain_left_edge          = [-4.31995267e+21 -4.31995267e+21 -4.31

CPU times: user 38 s, sys: 5.57 s, total: 43.5 s
Wall time: 1min 42s


In [ ]:
plot_

In [23]:
plot_files = [(dir+file_prfx+fname_plot+frmt_num).format(n) for dir,N in zip(dirss,Ns_done) for n in range(N)]

for file in plot_files[0]:
    ds = yt.load(file)
    try:
        file.particles_exist
    except:

    
        
    

In [ ]:
#once i read the files in and get the relevant variables, put the data in a table instead of rereading stuff through yt all over again

In [43]:
c_ts = [file.current_time.in_units('yr') for file in plot_files[0]]
r_ts = [file.current_time.in_units('yr') for file in plot_files[1]]
s_ts = [file.current_time.in_units('yr') for file in plot_files[2]]
e_ts = [file.current_time.in_units('yr') for file in plot_files[3]]

In [ ]:
#loop through the file, find the variable i need, and save that all within one loop, instead of opening all of them first THEN looping

In [91]:
for case,n in zip():
    sinkM_tot = []
    for i in range(201): #diff number for each feedback mechanism
        try:
            c_part_files[i].particles_exist
        except:
            c_sinkM_tot.append(0*yt.units.solMass)
        else:
            c_sinkM_tot.append(np.nansum(c_part_files[i].all_data()['particle_mass'].in_units('solMass')))
        finally:
            print(r_sinkM_tot[i])
    
    gasM_tot = [np.nansum(c_plot_files[i].all_data()['mass']).in_units('solMass') for i in range(201)] #diff number for each feedback mechanism

0 Msun
0 Msun
0 Msun
0 Msun
0 Msun
0 Msun
[1.17673087e+40 2.99109956e+40] g
[3.56129671e+40 2.82105997e+40 4.88992800e+40] g
[3.61860020e+40 7.04262511e+40 4.96116588e+40 6.68163170e+40] g
[6.89077819e+40 8.00580837e+40 7.17187240e+40 7.58623002e+40] g
[1.05370769e+41 9.86263031e+40 9.74770816e+40 2.72582461e+40
 8.82759629e+40] g
[1.20264212e+41 1.10164248e+41 1.14113534e+41 5.63828526e+40
 9.50689859e+40] g
[1.41720080e+41 1.28715043e+41 1.33501715e+41 8.57218224e+40
 1.01376422e+41] g
[1.82610578e+40 3.33325059e+39 1.69069425e+41 1.47517922e+41
 1.77042749e+41 1.18063872e+41 1.06246682e+41] g
[3.63291567e+40 1.11104790e+40 2.26285284e+41 1.69993018e+41
 2.35672111e+41 1.42001751e+41 1.11497966e+41] g
[4.82646633e+40 1.93646839e+40 2.79156975e+41 2.02418962e+41
 3.00492071e+41 1.66397164e+41 1.17907058e+41] g
[6.25399816e+40 2.80417236e+40 3.20421100e+41 2.25188167e+41
 3.40707766e+41 2.26761450e+40 1.99518988e+41 1.27889161e+41] g
[7.85879346e+40 3.84832966e+41 3.85509571e+40 2.6082

In [ ]:
r_sinkM_tot = []
for i in range(381): #diff number for each feedback mechanism
    try:
        r_part_files[i].particles_exist
    except:
        r_sinkM_tot.append(0*yt.units.solMass)
    else:
        r_sinkM_tot.append(np.nansum(r_part_files[i].all_data()['particle_mass'].in_units('solMass')))
    finally:
        print(r_sinkM_tot[i])

r_gasM_tot = [np.nansum(r_plot_files[i].all_data()['mass']).in_units('solMass') for i in range(381)] #diff number for each feedback mechanism

In [ ]:
#better to open a file, do all the operations, then move on, rather than open all the files and do one thing on all of them

In [ ]:
s_sinkMs = []
for i in range(130): #diff number for each feedback mechanism
    try:
        s_part_files[i].particles_exist
    except:
        s_sinkMs.append(0*yt.units.solMass)
    else:
        s_sinkMs.append(s_part_files[i].all_data()['particle_mass'])
    finally:
        print(s_sinkMs[i])

s_sinkM_tot = [np.nansum(s_sinkMs[i]).in_units('solMass') for i in range(130)]


s_gasM_tot = [np.nansum(s_plot_files[i].all_data()['mass']).in_units('solMass') for i in range(130)] #diff number for each feedback mechanism

In [ ]:
e_sinkMs = []
for i in range(63): #diff number for each feedback mechanism
    try:
        e_part_files[i].particles_exist
    except:
        e_sinkMs.append(0*yt.units.solMass)
    else:
        e_sinkMs.append(e_part_files[i].all_data()['particle_mass'])
    finally:
        print(e_sinkMs[i])

e_sinkM_tot = [np.nansum(e_sinkMs[i]).in_units('solMass') for i in range(63)]


e_gasM_tot = [np.nansum(e_plot_files[i].all_data()['mass']).in_units('solMass') for i in range(63)] #diff number for each feedback mechanism

In [ ]:
plt.rcParams['font.size'] = 15
plt.rcParams['font.family'] = 'STIXGeneral'
plt.rcParams['mathtext.fontset'] = 'stix'

In [ ]:
fig,axs = plt.subplots(2,2,dpi=300,figsize=(10,10))

for ax,t,m, in zip(axs.flat,[])
    ax.plot(ts,gas_mass,marker='.',label='gas',linewidth=0.1)
    ax.plot(ts,particle_mass_tot,marker='*',label='stars',linewidth=0.1)
    ax.loglog()
    ax.label_outer()

plt.legend()
fig.supxlabel('time [yr]')
ax.supylabel(r'mass [$M_\odot$]')

In [ ]:
plt.plot(ts,gas_mass,marker='.',label='gas',linewidth=0.1)
plt.plot(ts,particle_mass_tot,marker='*',label='stars',linewidth=0.1)
plt.loglog()
plt.legend()
plt.xlabel('time [yr]')
plt.ylabel(r'mass [$M_\odot$]')